### ISSUE TITLE
A lot of noisy message: `Updated the logging layer according to `log_config.json`

### ISSUE THREAD

**Issue by mrLSD** [near/workspaces-rs#272]
It is a lot of noisy log messages in the output:
```
Updated the logging layer according to `log_config.json`
```

Link to GitHub CI:
https://github.com/aurora-is-near/aurora-workspace/actions/runs/4893433957/jobs/8736389991#step:5:473

`no-capture` flag is not enabled.

Tested in 3 completely different projects. Same log message is in the output.

**Comment by itegulov** [comment]
Seems like this is happening because of https://github.com/near/nearcore/pull/8810. Not sure if there is a good way to silence this other than just not inheriting stdout from sandbox. @ChaoticTempest thoughts?

**Comment by ChaoticTempest** [comment]
yeah looks like we're just inheriting stdout by default for sandbox processes. A couple options we have for silencing it:
- set the sandbox proccess stdout to `Stdio::null` which just directs it to `/dev/null`, but nearcore might have informative stdout/stderr related info if it crashes or something can be added in the future, so probably not the best option.
- Since we have sandbox/network-builders now, we can have an extra parameter there saying whether or not to include stdout, with the default being not to include

**Comment by itsyaasir** [comment]
👋🏾  As per our discussion with @frol , I would like to take up this issue.

**Comment by frol** [comment]
Another option I would consider - fix it on nearcore side - avoid using println (use logging instead)

**Comment by itsyaasir** [comment]
> Another option I would consider - fix it on nearcore side - avoid using println (use logging instead)

Yeah, I think I will look into this.

**Comment by itsyaasir** [comment]
I have confirmed that the messages are no longer printed in the `stdout`. Attached is a screenshot with two commands.
- The first command is running with custom sandbox built against this branch, as you can see there's no println messages
- The second command is using the default sandbox and the print messages are there

PS:- The default version uses Commit hash for the sandbox "versioning", we will have to update the hash if we want to use the new sandbox which doesn't have the logging messages.

![Screenshot 2023-07-07 at 9 08 57 AM](https://github.com/near/nearcore/assets/7762687/5bdc3b99-2d92-4175-9c2f-537bb4aa2a44)

**Comment by mrLSD** [comment]
@itsyaasir is there a way to test it with `workspaces-rs`? Maybe git hash?

P.F. Out of discussion: what's the cool plugin for `zsh`? ))

**Comment by itsyaasir** [comment]
> @itsyaasir is there a way to test it with `workspaces-rs`? Maybe git hash?
> 
> P.F. Out of discussion: what's the cool plugin for `zsh`? ))

Unfortunately I don't have git hash, I can provide the sandbox that I used which I built it based on this [PR](https://github.com/near/nearcore/pull/9277). To get this changes in the workspace-rs, we need the PR merged and update the `near-sandbox-utils` to use the newer sandbox (from what I have seen). 

PS: It's not zsh plugin, I am using [starship-rs](https://starship.rs/) shell which has this nice simple preset and some customized icons.

**Comment by itsyaasir** [comment]
This issue can be closed.

**Comment by frol** [comment]
Resolved in https://github.com/near/nearcore/pull/9277

**Comment by mrLSD** [comment]
The issue is still online. [NEAR Issue](https://github.com/near/nearcore/issues/9143) was resolved, but we're still have same issue using workspace-rs. Any advice, please?
@frol  @itsyaasir

**Comment by shariffdev** [comment]
@mrLSD The main reason it is showing now is because workspace-rs is using an older sandbox, this [PR](https://github.com/near/workspaces-rs/pull/293) should get rid of the logging texts.
